// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jwt from "../auth/Jwt.res.mjs";
import * as OAuth2 from "../auth/OAuth2.res.mjs";
import * as AuthTypes from "../auth/AuthTypes.res.mjs";
import * as Assert1 from "jsr:@std/assert@1";

let Assert = {};

let $$Deno = {};

Deno.test("defaultRoles contains expected roles", () => {
  Assert1.assertEquals(AuthTypes.defaultRoles.length, 3);
  let roleNames = AuthTypes.defaultRoles.map(r => r.name);
  Assert1.assertEquals(roleNames.includes("admin"), true);
  Assert1.assertEquals(roleNames.includes("operator"), true);
  Assert1.assertEquals(roleNames.includes("viewer"), true);
});

Deno.test("admin role has wildcard permissions", () => {
  let adminRole = AuthTypes.defaultRoles.find(r => r.name === "admin");
  Assert1.assertExists(adminRole);
  if (adminRole !== undefined) {
    Assert1.assertEquals(adminRole.permissions.some(p => p.resource === "*"), true);
    return;
  }
});

Deno.test("decodeJwt parses valid JWT", () => {
  let headerObj = {
    alg: "RS256",
    typ: "JWT"
  };
  let header = btoa(JSON.stringify(headerObj));
  let payloadObj = {
    sub: "user123",
    iss: "https://auth.example.com",
    aud: "svalinn",
    exp: Date.now() / 1000.0 + 3600.0,
    iat: Date.now() / 1000.0
  };
  let payload = btoa(JSON.stringify(payloadObj));
  let token = header + `.` + payload + `.` + "test-signature";
  Jwt.decodeJwt(token);
  let decodedPayload = decoded.payload;
  Assert1.assertEquals(decodedHeader.alg, "RS256");
  Assert1.assertEquals(decodedPayload.sub, "user123");
  Assert1.assertEquals(decodedPayload.iss, "https://auth.example.com");
});

Deno.test("generateState creates random string", () => {
  let state1 = OAuth2.generateState();
  let state2 = OAuth2.generateState();
  Assert1.assertEquals(state1.length, 64);
  Assert1.assertEquals(state2.length, 64);
  Assert1.assertEquals(state1 !== state2, true);
});

Deno.test("getAuthorizationUrl generates correct URL", () => {
  let config_scopes = [
    "openid",
    "profile",
    "email"
  ];
  let config = {
    issuer: "https://auth.example.com",
    clientId: "test-client",
    clientSecret: "secret",
    authorizationEndpoint: "https://auth.example.com/authorize",
    tokenEndpoint: "https://auth.example.com/token",
    userInfoEndpoint: "https://auth.example.com/userinfo",
    jwksUri: "https://auth.example.com/.well-known/jwks.json",
    redirectUri: "https://svalinn.example.com/callback",
    scopes: config_scopes
  };
  let url = OAuth2.getAuthorizationUrl(config, "test-state", "test-nonce");
  Assert1.assertEquals(url.includes("response_type=code"), true);
  Assert1.assertEquals(url.includes("client_id=test-client"), true);
  Assert1.assertEquals(url.includes("state=test-state"), true);
  Assert1.assertEquals(url.includes("nonce=test-nonce"), true);
  Assert1.assertEquals(url.includes("scope=openid+profile+email"), true);
});

export {
  Assert,
  $$Deno,
}
/*  Not a pure module */
