// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as PolicyEvaluator from "../policy/PolicyEvaluator.res.mjs";
import * as Assert1 from "jsr:@std/assert@1";

let Assert = {};

let $$Deno = {};

let denyAllPolicy_registries = {
  allow: [],
  deny: ["*"],
  requireSignature: true
};

let denyAllPolicy_images = {
  allowPatterns: [],
  denyPatterns: ["*"],
  requireSbom: true
};

let denyAllPolicy_resources = {
  maxMemoryMb: 0,
  maxCpuCores: 0
};

let denyAllPolicy_security = {
  allowPrivileged: false,
  allowHostNetwork: false,
  allowHostPid: false,
  allowHostIpc: false,
  readOnlyRoot: true,
  dropCapabilities: ["ALL"],
  addCapabilities: []
};

let denyAllPolicy = {
  version: "1.0",
  name: "deny-all",
  registries: denyAllPolicy_registries,
  images: denyAllPolicy_images,
  resources: denyAllPolicy_resources,
  security: denyAllPolicy_security
};

let strictPolicy_registries = {
  allow: [
    "docker.io",
    "ghcr.io"
  ],
  deny: ["evil.registry.com"],
  requireSignature: true
};

let strictPolicy_images = {
  allowPatterns: ["*"],
  denyPatterns: ["*/test-*"],
  requireSbom: true
};

let strictPolicy_resources = {
  maxMemoryMb: 2048,
  maxCpuCores: 2
};

let strictPolicy_security = {
  allowPrivileged: false,
  allowHostNetwork: false,
  allowHostPid: false,
  allowHostIpc: false,
  readOnlyRoot: true,
  dropCapabilities: ["ALL"],
  addCapabilities: []
};

let strictPolicy = {
  version: "1.0",
  name: "strict",
  registries: strictPolicy_registries,
  images: strictPolicy_images,
  resources: strictPolicy_resources,
  security: strictPolicy_security
};

let permissivePolicy_registries = {
  allow: [],
  deny: [],
  requireSignature: false
};

let permissivePolicy_images = {
  allowPatterns: ["*"],
  denyPatterns: [],
  requireSbom: false
};

let permissivePolicy_resources = {
  maxMemoryMb: 65536,
  maxCpuCores: 64
};

let permissivePolicy_security = {
  allowPrivileged: true,
  allowHostNetwork: true,
  allowHostPid: true,
  allowHostIpc: true,
  readOnlyRoot: false,
  dropCapabilities: [],
  addCapabilities: []
};

let permissivePolicy = {
  version: "1.0",
  name: "permissive",
  registries: permissivePolicy_registries,
  images: permissivePolicy_images,
  resources: permissivePolicy_resources,
  security: permissivePolicy_security
};

Deno.test("default-deny: registry deny wildcard blocks any image", () => {
  let result = PolicyEvaluator.evaluate(denyAllPolicy, {
    image: "docker.io/library/alpine:3.18"
  });
  Assert1.assertEquals(result.allowed, false);
});

Deno.test("default-deny: empty allow list with non-empty deny list blocks explicit deny", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "evil.registry.com/malware:latest"
  });
  Assert1.assertEquals(result.allowed, false);
});

Deno.test("default-deny: unknown registry not in allow list is denied", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "unknown-registry.example/app:1.0"
  });
  Assert1.assertEquals(result.allowed, false);
  let hasRegistryViolation = result.violations.some(v => {
    if (v.rule === "registries.allow") {
      return true;
    } else {
      return v.rule === "registries.deny";
    }
  });
  Assert1.assertEquals(hasRegistryViolation, true);
});

Deno.test("privilege escalation: privileged flag rejected under strict policy", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "docker.io/library/alpine:3.18",
    privileged: true
  });
  Assert1.assertEquals(result.allowed, false);
  let hasPrivViolation = result.violations.some(v => v.rule === "security.allowPrivileged");
  Assert1.assertEquals(hasPrivViolation, true);
});

Deno.test("privilege escalation: privileged false does NOT trigger violation", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "docker.io/library/alpine:3.18",
    privileged: false
  });
  let hasPrivViolation = result.violations.some(v => v.rule === "security.allowPrivileged");
  Assert1.assertEquals(hasPrivViolation, false);
});

Deno.test("privilege escalation: permissive policy allows privileged without violation", () => {
  let result = PolicyEvaluator.evaluate(permissivePolicy, {
    image: "alpine:latest",
    privileged: true
  });
  let hasPrivViolation = result.violations.some(v => v.rule === "security.allowPrivileged");
  Assert1.assertEquals(hasPrivViolation, false);
});

Deno.test("policy integrity: deny-all policy applied correctly regardless of request claims", () => {
  let result = PolicyEvaluator.evaluate(denyAllPolicy, {
    image: "docker.io/library/alpine:3.18",
    privileged: false,
    hostNetwork: false,
    hostPid: false,
    hostIpc: false
  });
  Assert1.assertEquals(result.allowed, false);
});

Deno.test("policy integrity: request with registry field cannot override deny list", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "evil.registry.com/malware:latest",
    registry: "docker.io"
  });
  Assert1.assertEquals(result.appliedPolicy, "strict");
});

Deno.test("policy injection: glob pattern injection in registry allow list has no exec effect", () => {
  let newrecord = {...strictPolicy};
  newrecord.registries = {
    allow: [
      "$(rm -rf /)",
      "; DROP TABLE registries; --",
      "docker.io"
    ],
    deny: [],
    requireSignature: true
  };
  newrecord.name = "injected-strict";
  let result = PolicyEvaluator.evaluate(newrecord, {
    image: "docker.io/library/alpine:3.18"
  });
  Assert1.assertEquals(result.allowed, true);
});

Deno.test("policy injection: null-byte in registry name is not confused with allowed registry", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "docker.io\x00evil.com/malware:latest",
    registry: "docker.io\x00evil.com"
  });
  Assert1.assertExists(result);
});

Deno.test("wildcard boundary: '*' in allow list matches any registry", () => {
  let newrecord = {...strictPolicy};
  newrecord.registries = {
    allow: ["*"],
    deny: [],
    requireSignature: false
  };
  newrecord.name = "wildcard-allow";
  let result = PolicyEvaluator.evaluate(newrecord, {
    image: "random.obscure.registry.io/app:1.0"
  });
  let hasRegistryViolation = result.violations.some(v => v.rule === "registries.allow");
  Assert1.assertEquals(hasRegistryViolation, false);
});

Deno.test("wildcard boundary: '*.internal' should not match 'evil.external.com'", () => {
  let newrecord = {...strictPolicy};
  newrecord.registries = {
    allow: ["*.internal"],
    deny: [],
    requireSignature: false
  };
  newrecord.name = "internal-only";
  let result = PolicyEvaluator.evaluate(newrecord, {
    image: "evil.external.com/app:1.0"
  });
  let hasRegistryViolation = result.violations.some(v => v.rule === "registries.allow");
  Assert1.assertEquals(hasRegistryViolation, true);
});

Deno.test("wildcard boundary: '*.internal' matches 'registry.internal'", () => {
  let newrecord = {...strictPolicy};
  newrecord.registries = {
    allow: ["*.internal"],
    deny: [],
    requireSignature: false
  };
  newrecord.name = "internal-only";
  let result = PolicyEvaluator.evaluate(newrecord, {
    image: "registry.internal/app:1.0"
  });
  let hasRegistryViolation = result.violations.some(v => v.rule === "registries.allow");
  Assert1.assertEquals(hasRegistryViolation, false);
});

Deno.test("registry extraction: bare image name defaults to docker.io", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "alpine:3.18"
  });
  let hasRegistryViolation = result.violations.some(v => v.rule === "registries.allow");
  Assert1.assertEquals(hasRegistryViolation, false);
});

Deno.test("registry extraction: image with port uses full host:port as registry", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "localhost:5000/myapp:latest"
  });
  let hasRegistryViolation = result.violations.length !== 0;
  Assert1.assertEquals(hasRegistryViolation, true);
});

Deno.test("violation severity: registry deny violation is critical", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "evil.registry.com/malware:latest"
  });
  let criticalCount = result.violations.filter(v => v.severity === "critical").length;
  Assert1.assertEquals(criticalCount > 0, true);
});

Deno.test("violation severity: privileged violation is critical", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "docker.io/library/alpine:3.18",
    privileged: true
  });
  let privViolation = result.violations.find(v => v.rule === "security.allowPrivileged");
  if (privViolation !== undefined) {
    Assert1.assertEquals(privViolation.severity, "critical");
  } else {
    Assert1.assertEquals(true, false);
  }
});

Deno.test("policyResult: appliedPolicy matches policy name", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "docker.io/library/alpine:3.18"
  });
  Assert1.assertEquals(result.appliedPolicy, "strict");
});

Deno.test("policyResult: evaluatedAt is a non-empty numeric string", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "docker.io/library/alpine:3.18"
  });
  Assert1.assertEquals(result.evaluatedAt.length > 0, true);
  let parsed = Stdlib_Float.fromString(result.evaluatedAt);
  Assert1.assertEquals(Stdlib_Option.isSome(parsed), true);
});

Deno.test("policyResult: allowed=true implies zero critical/high violations", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "docker.io/library/alpine:3.18"
  });
  if (!result.allowed) {
    return;
  }
  let hasCriticalOrHigh = result.violations.some(v => {
    if (v.severity === "critical") {
      return true;
    } else {
      return v.severity === "high";
    }
  });
  Assert1.assertEquals(hasCriticalOrHigh, false);
});

Deno.test("policyResult: allowed=false implies at least one critical or high violation", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "evil.registry.com/malware:latest",
    privileged: true
  });
  Assert1.assertEquals(result.allowed, false);
  let hasCriticalOrHigh = result.violations.some(v => {
    if (v.severity === "critical") {
      return true;
    } else {
      return v.severity === "high";
    }
  });
  Assert1.assertEquals(hasCriticalOrHigh, true);
});

export {
  Assert,
  $$Deno,
  denyAllPolicy,
  strictPolicy,
  permissivePolicy,
}
/*  Not a pure module */
