// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "../vordr/Client.res.mjs";
import * as Validation from "../validation/Validation.res.mjs";
import * as ClientResMjs from "../vordr/Client.res.mjs";

let vordrClient = ClientResMjs.client;

async function healthHandler() {
  let vordrConnected = await Client.ping(vordrClient);
  return {
    status: "healthy",
    version: "0.1.0",
    vordrConnected: vordrConnected,
    timestamp: Date.now().toString()
  };
}

async function containersHandler() {
  return await Client.listContainers(vordrClient);
}

async function imagesHandler() {
  return await Client.listImages(vordrClient);
}

async function runHandler(request) {
  await Validation.validateRunRequest(request);
  await Client.verifyImage(vordrClient, request.imageName, request.imageDigest);
  return await Client.runContainer(vordrClient, request);
}

async function verifyHandler(request) {
  return await Client.verifyImage(vordrClient, request.imageRef, "");
}

async function stopHandler(containerId) {
  return await Client.stopContainer(vordrClient, containerId);
}

async function removeHandler(containerId) {
  return await Client.removeContainer(vordrClient, containerId);
}

async function inspectHandler(containerId) {
  return await Client.inspectContainer(vordrClient, containerId);
}

export {
  vordrClient,
  healthHandler,
  containersHandler,
  imagesHandler,
  runHandler,
  verifyHandler,
  stopHandler,
  removeHandler,
  inspectHandler,
}
/* vordrClient Not a pure module */
