// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Yaml1 from "jsr:@std/yaml@^1";

let Yaml = {};

let Path = {};

let $$Deno = {};

function make(endpointOpt) {
  let endpoint = endpointOpt !== undefined ? endpointOpt : "http://localhost:8000";
  return {
    svalinnEndpoint: endpoint,
    projects: new Map()
  };
}

async function loadComposeFile(filePath) {
  let content = await Deno.readTextFile(filePath);
  let parsed = Yaml1.parse(content);
  if (parsed.version !== "1.0") {
    Pervasives.failwith(`Unsupported compose version: ` + parsed.version + `. Expected 1.0`);
  }
  return parsed;
}

async function callSvalinn(self, method, path, body) {
  let url = self.svalinnEndpoint + path;
  let options = {
    method: method,
    headers: {
      "Content-Type": "application/json"
    },
    body: body !== undefined ? JSON.stringify(body) : undefined
  };
  let response = await fetch(url, options);
  if (!response.ok) {
    Pervasives.failwith(`Svalinn API error: ` + response.status.toString());
  }
  return await response.json();
}

async function up(self, composeFile) {
  let startTime = Date.now();
  let projectName = Core__Option.getOr(composeFile.name, "default");
  console.log(`Starting project: ` + projectName);
  return {
    success: true,
    project: projectName,
    services: [],
    networks: [],
    volumes: [],
    duration: Date.now() - startTime
  };
}

let Orchestrator = {
  make: make,
  loadComposeFile: loadComposeFile,
  callSvalinn: callSvalinn,
  up: up
};

export {
  Yaml,
  Path,
  $$Deno,
  Orchestrator,
}
/* jsr:@std/yaml@^1 Not a pure module */
