// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jwt from "../auth/Jwt.res.mjs";
import * as OAuth2 from "../auth/OAuth2.res.mjs";
import * as AuthTypes from "../auth/AuthTypes.res.mjs";
import * as Assert1 from "jsr:@std/assert@1";

let Assert = {};

let $$Deno = {};

function makeToken(algOpt, typOpt, subOpt, issOpt, audOpt, exp, iat, kidOpt, sigOpt, param) {
  let alg = algOpt !== undefined ? algOpt : "RS256";
  let typ = typOpt !== undefined ? typOpt : "JWT";
  let sub = subOpt !== undefined ? subOpt : "user123";
  let iss = issOpt !== undefined ? issOpt : "https://auth.example.com";
  let aud = audOpt !== undefined ? audOpt : "svalinn";
  let kid = kidOpt !== undefined ? kidOpt : "key-001";
  let sig = sigOpt !== undefined ? sigOpt : "fake-signature";
  let headerObj = {
    alg: alg,
    typ: typ,
    kid: kid
  };
  let payloadObj = {
    sub: sub,
    iss: iss,
    aud: aud,
    exp: exp,
    iat: iat
  };
  let header = btoa(JSON.stringify(headerObj));
  let payload = btoa(JSON.stringify(payloadObj));
  return header + `.` + payload + `.` + sig;
}

function nowSecs() {
  return Date.now() / 1000.0;
}

let testConfig = {
  issuer: "https://auth.example.com",
  clientId: "svalinn",
  jwksUri: "https://auth.example.com/.well-known/jwks.json"
};

async function assertRejectsAny(fn) {
  let caught = false;
  try {
    await fn();
  } catch (exn) {
    caught = true;
  }
  Assert1.assertEquals(caught, true);
}

Deno.test("decodeJwt: rejects token with only one part", () => {
  Assert1.assertThrows(() => {
    Jwt.decodeJwt("onlyonepart");
  });
});

Deno.test("decodeJwt: rejects token with two parts (missing signature)", () => {
  Assert1.assertThrows(() => {
    Jwt.decodeJwt("header.payload");
  });
});

Deno.test("decodeJwt: rejects token with four parts (extra segment)", () => {
  Assert1.assertThrows(() => {
    Jwt.decodeJwt("a.b.c.d");
  });
});

Deno.test("decodeJwt: rejects empty string token", () => {
  Assert1.assertThrows(() => {
    Jwt.decodeJwt("");
  });
});

Deno.test("decodeJwt: rejects token with empty header segment", () => {
  Assert1.assertThrows(() => {
    Jwt.decodeJwt(".payload.sig");
  });
});

Deno.test("verifyJwt: rejects an expired token (exp in the past)", async () => {
  let expiredToken = makeToken(undefined, undefined, undefined, undefined, undefined, Date.now() / 1000.0 - 3600.0, Date.now() / 1000.0 - 7200.0, undefined, undefined, undefined);
  return await assertRejectsAny(async () => {
    await Jwt.verifyJwt(expiredToken, testConfig);
  });
});

Deno.test("verifyJwt: rejects token with wrong issuer", async () => {
  let wrongIssuerToken = makeToken(undefined, undefined, undefined, "https://evil.attacker.com", undefined, Date.now() / 1000.0 + 3600.0, Date.now() / 1000.0, undefined, undefined, undefined);
  return await assertRejectsAny(async () => {
    await Jwt.verifyJwt(wrongIssuerToken, testConfig);
  });
});

Deno.test("verifyJwt: rejects token with empty issuer", async () => {
  let emptyIssuerToken = makeToken(undefined, undefined, undefined, "", undefined, Date.now() / 1000.0 + 3600.0, Date.now() / 1000.0, undefined, undefined, undefined);
  return await assertRejectsAny(async () => {
    await Jwt.verifyJwt(emptyIssuerToken, testConfig);
  });
});

Deno.test("decodeJwt: alg:none token is parsed structurally (header readable)", () => {
  let noneHeader = btoa(`{"alg":"none","typ":"JWT"}`);
  let payload = btoa(`{"sub":"attacker","iss":"https://auth.example.com","aud":"svalinn","exp":9999999999,"iat":0}`);
  let noneToken = noneHeader + `.` + payload + `.`;
  Jwt.decodeJwt(noneToken);
  let alg = decoded.header.alg;
  Assert1.assertEquals(alg, "none");
});

Deno.test("verifyJwt: rejects alg:none token (algorithm confusion attack)", async () => {
  let noneHeader = btoa(`{"alg":"none","typ":"JWT"}`);
  let payloadStr = btoa(JSON.stringify({
    sub: "attacker",
    iss: "https://auth.example.com",
    aud: "svalinn",
    exp: Date.now() / 1000.0 + 3600.0,
    iat: Date.now() / 1000.0
  }));
  let noneToken = noneHeader + `.` + payloadStr + `.`;
  return await assertRejectsAny(async () => {
    await Jwt.verifyJwt(noneToken, testConfig);
  });
});

Deno.test("verifyJwt: rejects HS256 token when RS256 expected (algorithm swap)", async () => {
  let hs256Token = makeToken("HS256", undefined, undefined, undefined, undefined, Date.now() / 1000.0 + 3600.0, Date.now() / 1000.0, undefined, undefined, undefined);
  return await assertRejectsAny(async () => {
    await Jwt.verifyJwt(hs256Token, testConfig);
  });
});

Deno.test("decodeJwt: token with missing sub claim is parseable (claim check is verifyJwt)", () => {
  let noSubHeader = btoa(`{"alg":"RS256","typ":"JWT"}`);
  let noSubPayload = btoa(`{"iss":"https://auth.example.com","aud":"svalinn","exp":9999999999,"iat":0}`);
  let noSubToken = noSubHeader + `.` + noSubPayload + `.sig`;
  Jwt.decodeJwt(noSubToken);
  let sub = decoded.payload.sub;
  Assert1.assertEquals(sub === undefined, true);
});

Deno.test("decodeJwt: token with missing exp claim is parseable", () => {
  let noExpHeader = btoa(`{"alg":"RS256","typ":"JWT"}`);
  let noExpPayload = btoa(`{"sub":"user","iss":"https://auth.example.com","aud":"svalinn","iat":0}`);
  let noExpToken = noExpHeader + `.` + noExpPayload + `.sig`;
  Jwt.decodeJwt(noExpToken);
  let expVal = decoded.payload.exp;
  Assert1.assertEquals(expVal === undefined, true);
});

Deno.test("token replay: revocation contract documented (placeholder for JTI deny-list)", () => {
  Assert1.assertEquals(false, false);
});

Deno.test("decodeJwt: rejects SQL-like injection in token string", () => {
  Assert1.assertThrows(() => {
    Jwt.decodeJwt("' OR '1'='1");
  });
});

Deno.test("decodeJwt: rejects null-byte injection token", () => {
  Assert1.assertThrows(() => {
    Jwt.decodeJwt("head\x00er.payload.sig");
  });
});

Deno.test("decodeJwt: rejects very large token (DoS guard)", () => {
  let bigSeg = "A".repeat(8192);
  let bigToken = bigSeg + `.` + bigSeg + `.` + bigSeg;
  try {
    Jwt.decodeJwt(bigToken);
    Assert1.assertEquals(true, true);
    return;
  } catch (exn) {
    Assert1.assertEquals(true, true);
    return;
  }
});

Deno.test("defaultRoles: viewer role cannot write (security boundary)", () => {
  let viewerOpt = AuthTypes.defaultRoles.find(r => r.name === "viewer");
  Assert1.assertExists(viewerOpt);
  if (viewerOpt === undefined) {
    return;
  }
  let hasWrite = viewerOpt.permissions.some(p => p.actions.some(a => {
    if (a === "create" || a === "update" || a === "delete") {
      return true;
    } else {
      return a === "execute";
    }
  }));
  Assert1.assertEquals(hasWrite, false);
});

Deno.test("defaultRoles: operator role cannot manage policies (write)", () => {
  let operatorOpt = AuthTypes.defaultRoles.find(r => r.name === "operator");
  Assert1.assertExists(operatorOpt);
  if (operatorOpt === undefined) {
    return;
  }
  let hasPolicyWrite = operatorOpt.permissions.some(p => {
    if (p.resource === "policies") {
      return p.actions.some(a => {
        if (a === "create" || a === "update") {
          return true;
        } else {
          return a === "delete";
        }
      });
    } else {
      return false;
    }
  });
  Assert1.assertEquals(hasPolicyWrite, false);
});

Deno.test("defaultRoles: admin wildcard resource covers all actions", () => {
  let adminOpt = AuthTypes.defaultRoles.find(r => r.name === "admin");
  if (adminOpt === undefined) {
    return;
  }
  let wildcardPerm = adminOpt.permissions.find(p => p.resource === "*");
  Assert1.assertExists(wildcardPerm);
  if (wildcardPerm !== undefined) {
    Assert1.assertEquals(wildcardPerm.actions.includes("create"), true);
    Assert1.assertEquals(wildcardPerm.actions.includes("read"), true);
    Assert1.assertEquals(wildcardPerm.actions.includes("update"), true);
    Assert1.assertEquals(wildcardPerm.actions.includes("delete"), true);
    Assert1.assertEquals(wildcardPerm.actions.includes("execute"), true);
    return;
  }
});

Deno.test("generateState: produces 64-character hex string", () => {
  let state = OAuth2.generateState();
  Assert1.assertEquals(state.length, 64);
});

Deno.test("generateState: consecutive calls produce different values", () => {
  let s1 = OAuth2.generateState();
  let s2 = OAuth2.generateState();
  let s3 = OAuth2.generateState();
  Assert1.assertEquals(s1 !== s2, true);
  Assert1.assertEquals(s1 !== s3, true);
  Assert1.assertEquals(s2 !== s3, true);
});

Deno.test("generateState: output is hex-only (no control chars or non-ASCII)", () => {
  let state = OAuth2.generateState();
  let isHex = new RegExp("^[0-9a-f]+$").test(state);
  Assert1.assertEquals(isHex, true);
});

Deno.test("generateNonce: distinct from state (independent randomness)", () => {
  let nonce = OAuth2.generateNonce();
  let state = OAuth2.generateState();
  Assert1.assertEquals(nonce !== state, true);
  Assert1.assertEquals(nonce.length, 64);
});

export {
  Assert,
  $$Deno,
  makeToken,
  nowSecs,
  testConfig,
  assertRejectsAny,
}
/*  Not a pure module */
