// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PolicyEvaluator from "../policy/PolicyEvaluator.res.mjs";
import * as Assert1 from "jsr:@std/assert@1";

let Assert = {};

let $$Deno = {};

let strictPolicy_registries = {
  allow: [
    "docker.io",
    "ghcr.io"
  ],
  deny: ["evil.registry.com"],
  requireSignature: true
};

let strictPolicy_images = {
  allowPatterns: ["*"],
  denyPatterns: ["*/test-*"],
  requireSbom: true
};

let strictPolicy_resources = {
  maxMemoryMb: 2048,
  maxCpuCores: 2
};

let strictPolicy_security = {
  allowPrivileged: false,
  allowHostNetwork: false,
  allowHostPid: false,
  allowHostIpc: false,
  readOnlyRoot: true,
  dropCapabilities: ["ALL"],
  addCapabilities: []
};

let strictPolicy = {
  version: "1.0",
  name: "strict",
  registries: strictPolicy_registries,
  images: strictPolicy_images,
  resources: strictPolicy_resources,
  security: strictPolicy_security
};

let permissivePolicy_registries = {
  allow: [],
  deny: [],
  requireSignature: false
};

let permissivePolicy_images = {
  allowPatterns: ["*"],
  denyPatterns: [],
  requireSbom: false
};

let permissivePolicy_resources = {
  maxMemoryMb: 16384,
  maxCpuCores: 8
};

let permissivePolicy_security = {
  allowPrivileged: true,
  allowHostNetwork: true,
  allowHostPid: true,
  allowHostIpc: true,
  readOnlyRoot: false,
  dropCapabilities: [],
  addCapabilities: []
};

let permissivePolicy = {
  version: "1.0",
  name: "permissive",
  registries: permissivePolicy_registries,
  images: permissivePolicy_images,
  resources: permissivePolicy_resources,
  security: permissivePolicy_security
};

Deno.test("strict policy allows docker.io images", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "docker.io/library/alpine:3.18"
  });
  Assert1.assertEquals(result.allowed, true);
});

Deno.test("strict policy denies unknown registry", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "evil.registry.com/malware:latest"
  });
  Assert1.assertEquals(result.allowed, false);
  Assert1.assertEquals(result.violations.some(v => v.rule === "registries.deny"), true);
});

Deno.test("strict policy denies privileged containers", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "alpine:3.18",
    privileged: true
  });
  Assert1.assertEquals(result.allowed, false);
  Assert1.assertEquals(result.violations.some(v => v.rule === "security.allowPrivileged"), true);
});

Deno.test("permissive policy allows privileged", () => {
  let result = PolicyEvaluator.evaluate(permissivePolicy, {
    image: "alpine:latest",
    privileged: true
  });
  Assert1.assertEquals(result.allowed, true);
});

Deno.test("extracts docker.io from short image name", () => {
  let result = PolicyEvaluator.evaluate(strictPolicy, {
    image: "alpine:3.18"
  });
  Assert1.assertEquals(result.allowed, true);
});

export {
  Assert,
  $$Deno,
  strictPolicy,
  permissivePolicy,
}
/*  Not a pure module */
