// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tools from "./Tools.res.mjs";
import * as Client from "../vordr/Client.res.mjs";
import * as Validation from "../validation/Validation.res.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let serverName = "svalinn";

let serverVersion = "0.1.0";

let protocolVersion = "2024-11-05";

function handleInitialize(_params) {
  return {
    protocolVersion: protocolVersion,
    capabilities: {
      tools: {}
    },
    serverInfo: {
      name: serverName,
      version: serverVersion
    }
  };
}

function handleListTools() {
  return {
    tools: Tools.allTools
  };
}

function makeSuccess(text) {
  return {
    content: [{
        type_: "text",
        text: text
      }],
    isError: undefined
  };
}

function makeError(text) {
  return {
    content: [{
        type_: "text",
        text: text
      }],
    isError: true
  };
}

function handlePolicy(args) {
  let action = args.action;
  switch (action) {
    case "get" :
      return makeSuccess(JSON.stringify(Validation.defaultPolicy));
    case "validate" :
      return {
        content: [{
            type_: "text",
            text: "Policy valid"
          }],
        isError: undefined
      };
    default:
      return makeError(`Unknown policy action: ` + action);
  }
}

async function handleVerify(args) {
  let image = args.image;
  try {
    let result = await Client.verifyImage(Client.client, image, "");
    if (result.verified) {
      return makeSuccess(`Image verified: ` + image);
    } else {
      return makeError(`Image verification failed: ` + image);
    }
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return makeError(Stdlib_Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error"));
    }
    throw e;
  }
}

async function handleStop(args) {
  let containerId = args.containerId;
  try {
    await Client.stopContainer(Client.client, containerId);
    return makeSuccess(`Container stopped: ` + containerId);
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return makeError(Stdlib_Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error"));
    }
    throw e;
  }
}

async function handlePs(_args) {
  let containers = await Client.listContainers(Client.client);
  return makeSuccess(containers.length === 0 ? "No containers running" : containers.map(c => c.id + `\t` + c.name + `\t` + c.image).join("\n"));
}

async function handleRun(args) {
  let image = args.image;
  let name = args.name;
  if (!Validation.isAllowedRegistry(image, Validation.defaultPolicy)) {
    return {
      content: [{
          type_: "text",
          text: "Image from disallowed registry"
        }],
      isError: true
    };
  }
  if (Validation.isDeniedImage(image, Validation.defaultPolicy)) {
    return {
      content: [{
          type_: "text",
          text: "Image is in deny list"
        }],
      isError: true
    };
  }
  let request_detach = args.detach;
  let request_removeOnExit = args.removeOnExit;
  let request = {
    imageName: image,
    imageDigest: "",
    name: name,
    command: undefined,
    env: undefined,
    detach: request_detach,
    removeOnExit: request_removeOnExit,
    profile: undefined
  };
  try {
    let containerInfo = await Client.runContainer(Client.client, request);
    return makeSuccess(`Container started: ` + containerInfo.id);
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return makeError(Stdlib_Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error"));
    }
    throw e;
  }
}

async function handleRm(args) {
  let containerId = args.containerId;
  try {
    await Client.removeContainer(Client.client, containerId);
    return makeSuccess(`Container removed: ` + containerId);
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return makeError(Stdlib_Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error"));
    }
    throw e;
  }
}

async function handleLogs(args) {
  return {
    content: [{
        type_: "text",
        text: "Logs not yet implemented"
      }],
    isError: undefined
  };
}

async function handleExec(args) {
  return {
    content: [{
        type_: "text",
        text: "Exec not yet implemented"
      }],
    isError: undefined
  };
}

async function handleCallTool(params) {
  let name = params.name;
  let $$arguments = params.arguments;
  switch (name) {
    case "svalinn_exec" :
      return await handleExec($$arguments);
    case "svalinn_logs" :
      return await handleLogs($$arguments);
    case "svalinn_policy" :
      return handlePolicy($$arguments);
    case "svalinn_ps" :
      return await handlePs($$arguments);
    case "svalinn_rm" :
      return await handleRm($$arguments);
    case "svalinn_run" :
      return await handleRun($$arguments);
    case "svalinn_stop" :
      return await handleStop($$arguments);
    case "svalinn_verify" :
      return await handleVerify($$arguments);
    default:
      return makeError(`Unknown tool: ` + name);
  }
}

async function handleRequest(request) {
  let method = request.method;
  let result;
  switch (method) {
    case "initialize" :
      result = handleInitialize(request.params);
      break;
    case "tools/call" :
      let p = request.params;
      result = p !== undefined ? await handleCallTool(p) : ({
          content: [{
              type_: "text",
              text: "Missing params for tools/call"
            }],
          isError: true
        });
      break;
    case "tools/list" :
      result = {
        tools: Tools.allTools
      };
      break;
    default:
      result = makeError(`Unknown method: ` + method);
  }
  return {
    jsonrpc: "2.0",
    result: result,
    error: undefined,
    id: request.id
  };
}

export {
  serverName,
  serverVersion,
  protocolVersion,
  handleInitialize,
  handleListTools,
  handleCallTool,
  handleRun,
  handlePs,
  handleStop,
  handleVerify,
  handlePolicy,
  handleLogs,
  handleExec,
  handleRm,
  makeSuccess,
  makeError,
  handleRequest,
}
/* Client Not a pure module */
