// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ValidatorMjs from "./validator.mjs";

let runRequestSchema = "gateway-run-request.v1.json";

let verifyRequestSchema = "gateway-verify-request.v1.json";

function validate(prim0, prim1) {
  return ValidatorMjs.validate(prim0, prim1);
}

function loadSchemas(prim) {
  return ValidatorMjs.loadSchemas(prim);
}

async function validateRunRequest(request) {
  return await ValidatorMjs.validate(runRequestSchema, request);
}

async function validateVerifyRequest(request) {
  return await ValidatorMjs.validate(verifyRequestSchema, request);
}

function isValid(result) {
  return typeof result !== "object";
}

function getErrors(result) {
  if (typeof result !== "object") {
    return [];
  } else {
    return result._0;
  }
}

let containerInfoSchema = "container-info.v1.json";

let errorResponseSchema = "error-response.v1.json";

export {
  runRequestSchema,
  verifyRequestSchema,
  containerInfoSchema,
  errorResponseSchema,
  validate,
  loadSchemas,
  validateRunRequest,
  validateVerifyRequest,
  isValid,
  getErrors,
}
/* ./validator.mjs Not a pure module */
