// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Schema from "./Schema.res.mjs";

let defaultPolicy_maxMemoryMb = 4096;

let defaultPolicy_maxCpuCores = 4.0;

let defaultPolicy_allowedRegistries = [
  "docker.io",
  "ghcr.io",
  "quay.io",
  "gcr.io"
];

let defaultPolicy_deniedImages = [];

let defaultPolicy = {
  allowPrivileged: false,
  allowHostNetwork: false,
  allowHostPid: false,
  maxMemoryMb: defaultPolicy_maxMemoryMb,
  maxCpuCores: defaultPolicy_maxCpuCores,
  allowedRegistries: defaultPolicy_allowedRegistries,
  deniedImages: defaultPolicy_deniedImages
};

function isAllowedRegistry(imageRef, _policy) {
  let r = imageRef.split("/")[0];
  let registry = r !== undefined ? r : "docker.io";
  if (_policy.allowedRegistries.length === 0) {
    return true;
  } else {
    return _policy.allowedRegistries.some(r => r === registry);
  }
}

function isDeniedImage(imageRef, _policy) {
  return _policy.deniedImages.some(img => imageRef.includes(img));
}

function validatePolicy(_request, _policy) {
  let violations = [];
  if (violations.length === 0) {
    return "Allowed";
  } else {
    return {
      TAG: "Denied",
      _0: violations
    };
  }
}

async function validateRequest(schemaName, request, policy) {
  let schemaResult = await Schema.validate(schemaName, request);
  let policyResult = validatePolicy(request, policy);
  return [
    schemaResult,
    policyResult
  ];
}

let runRequestSchema = Schema.runRequestSchema;

let verifyRequestSchema = Schema.verifyRequestSchema;

let containerInfoSchema = Schema.containerInfoSchema;

let errorResponseSchema = Schema.errorResponseSchema;

let validate = Schema.validate;

let loadSchemas = Schema.loadSchemas;

let validateRunRequest = Schema.validateRunRequest;

let validateVerifyRequest = Schema.validateVerifyRequest;

let isValid = Schema.isValid;

let getErrors = Schema.getErrors;

export {
  runRequestSchema,
  verifyRequestSchema,
  containerInfoSchema,
  errorResponseSchema,
  validate,
  loadSchemas,
  validateRunRequest,
  validateVerifyRequest,
  isValid,
  getErrors,
  defaultPolicy,
  isAllowedRegistry,
  isDeniedImage,
  validatePolicy,
  validateRequest,
}
/* Schema Not a pure module */
