// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as HandlersMjs from "./handlers.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function configFromEnv() {
  let getEnvOr = (key, $$default) => {
    let v = (Deno.env.toObject())[key];
    if (v !== undefined) {
      return Primitive_option.valFromOption(v);
    } else {
      return $$default;
    }
  };
  return {
    port: Stdlib_Option.getOr(Stdlib_Int.fromString(getEnvOr("SVALINN_PORT", "8000"), undefined), 8000),
    host: getEnvOr("SVALINN_HOST", "0.0.0.0"),
    vordrEndpoint: getEnvOr("VORDR_ENDPOINT", "http://localhost:8080"),
    specVersion: getEnvOr("SPEC_VERSION", "v0.1.0")
  };
}

function healthHandler(prim) {
  return HandlersMjs.healthHandler();
}

function containersHandler(prim) {
  return HandlersMjs.containersHandler();
}

function imagesHandler(prim) {
  return HandlersMjs.imagesHandler();
}

function runHandler(prim) {
  return HandlersMjs.runHandler(prim);
}

function verifyHandler(prim) {
  return HandlersMjs.verifyHandler(prim);
}

function stopHandler(prim) {
  return HandlersMjs.stopHandler(prim);
}

function removeHandler(prim) {
  return HandlersMjs.removeHandler(prim);
}

function inspectHandler(prim) {
  return HandlersMjs.inspectHandler(prim);
}

let $$Deno = {};

let defaultConfig = {
  port: 8000,
  host: "0.0.0.0",
  vordrEndpoint: "http://localhost:8080",
  specVersion: "v0.1.0"
};

export {
  defaultConfig,
  configFromEnv,
  healthHandler,
  containersHandler,
  imagesHandler,
  runHandler,
  verifyHandler,
  stopHandler,
  removeHandler,
  inspectHandler,
  $$Deno,
}
/* ./handlers.mjs Not a pure module */
