// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE


let Env = {};

let Fs = {};

let Http = {};

let Io = {};

let AbortController = {};

export {
  Env,
  Fs,
  Http,
  Io,
  AbortController,
}
/* No side effect */
