// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE


let Headers = {};

let Body = {};

let Request = {};

function json_res(data, statusOpt, param) {
  let status = statusOpt !== undefined ? statusOpt : 200;
  return globalThis.Response.json(data, {
    status: status,
    headers: {
      "Content-Type": "application/json"
    }
  });
}

let Response = {
  json_res: json_res
};

export {
  Headers,
  Body,
  Request,
  Response,
}
/* No side effect */
