// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

let keyTrustHierarchy = [
  "untrusted",
  "self-signed",
  "organization",
  "trusted-keyring",
  "hardware-backed",
  "fulcio-verified"
];

function meetsKeyTrustLevel(actual, required) {
  let actualIndex = keyTrustHierarchy.indexOf(actual);
  let requiredIndex = keyTrustHierarchy.indexOf(required);
  return actualIndex >= requiredIndex;
}

function matchGlob(pattern, value) {
  let regexPattern = pattern.replace(/[.+^${}()|[\\]\\\\]/g, "\\$&").replace(/\\*/g, ".*").replace(/\\?/g, ".");
  return new RegExp(`^` + regexPattern + `$`).test(value);
}

function matchPatterns(patterns, value) {
  return patterns.some(p => matchGlob(p, value));
}

function extractRegistry(image) {
  let parts = image.split("/");
  if (parts.length === 1) {
    return "docker.io";
  }
  let first = Belt_Array.getExn(parts, 0);
  if (first.includes(".") || first.includes(":")) {
    return first;
  } else {
    return "docker.io";
  }
}

let Helpers = {
  keyTrustHierarchy: keyTrustHierarchy,
  meetsKeyTrustLevel: meetsKeyTrustLevel,
  matchGlob: matchGlob,
  matchPatterns: matchPatterns,
  extractRegistry: extractRegistry
};

function evaluate(policy, request) {
  let violations = [];
  let registry = Core__Option.getOr(request.registry, extractRegistry(request.image));
  if (policy.registries.deny.length > 0 && matchPatterns(policy.registries.deny, registry)) {
    violations.push({
      rule: "registries.deny",
      severity: "critical",
      message: `Registry '` + registry + `' is in the deny list`,
      field: "registry",
      actual: registry
    });
  }
  if (policy.registries.allow.length > 0 && !matchPatterns(policy.registries.allow, registry)) {
    violations.push({
      rule: "registries.allow",
      severity: "critical",
      message: `Registry '` + registry + `' is not in the allow list`,
      field: "registry",
      actual: registry,
      expected: policy.registries.allow.map(prim => prim)
    });
  }
  if (Core__Option.getOr(request.privileged, false) && !policy.security.allowPrivileged) {
    violations.push({
      rule: "security.allowPrivileged",
      severity: "critical",
      message: "Privileged containers are not allowed",
      field: "privileged",
      actual: true,
      expected: false
    });
  }
  let hasCritical = violations.some(v => v.severity === "critical");
  let hasHigh = violations.some(v => v.severity === "high");
  return {
    allowed: !hasCritical && !hasHigh,
    violations: violations,
    appliedPolicy: policy.name,
    evaluatedAt: Date.now().toString()
  };
}

export {
  Helpers,
  evaluate,
}
/* No side effect */
