// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE


let $$Deno = {};

function make(policyDir) {
  return {
    policyDir: policyDir,
    cache: new Map()
  };
}

async function loadPolicy(self, name) {
  let p = self.cache.get(name);
  if (p !== undefined) {
    return p;
  }
  try {
    let path = self.policyDir + `/` + name + `.json`;
    let content = await Deno.readTextFile(path);
    let policy = JSON.parse(content);
    self.cache.set(name, policy);
    return policy;
  } catch (exn) {
    return;
  }
}

async function listPolicies(self) {
  let policies = [];
  Deno.readDir(self.policyDir);
  ((async function() {
        for await (const entry of iter) {
          if (entry.isFile && entry.name.endsWith(".json")) {
            policies.push(entry.name.replace(".json", ""));
          }
        }
      })());
  return policies;
}

let PolicyStore = {
  make: make,
  loadPolicy: loadPolicy,
  listPolicies: listPolicies
};

export {
  $$Deno,
  PolicyStore,
}
/* No side effect */
