// Generated by ReScript, PLEASE EDIT WITH CARE


let Types = {};

let $$Deno = {};

function make(ctPathOpt, runtimeOpt, trustStore, policy, param) {
  let ctPath = ctPathOpt !== undefined ? ctPathOpt : "ct";
  let runtime = runtimeOpt !== undefined ? runtimeOpt : "svalinn";
  return {
    ctPath: ctPath,
    defaultRuntime: runtime,
    trustStorePath: trustStore,
    policyPath: policy
  };
}

async function isAvailable(self) {
  try {
    let cmd = new (Deno.Command)(self.ctPath, {
      args: ["version"]
    });
    let out = await cmd.output();
    return out.code === 0;
  } catch (exn) {
    return false;
  }
}

async function verify(self, bundlePath) {
  let args = [
    "verify",
    bundlePath
  ];
  let cmd = new (Deno.Command)(self.ctPath, {
    args: args
  });
  let out = await cmd.output();
  return {
    valid: out.code === 0,
    exitCode: "SUCCESS",
    bundle: bundlePath,
    checks: [],
    timestamp: Date.now().toString()
  };
}

let CerroTorre = {
  make: make,
  isAvailable: isAvailable,
  verify: verify
};

export {
  Types,
  $$Deno,
  CerroTorre,
}
/* No side effect */
