// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";

let Types = {};

let runtimePriority = [
  "nerdctl",
  "podman",
  "docker"
];

function make(endpointOpt) {
  let endpoint = endpointOpt !== undefined ? endpointOpt : "http://localhost:3000";
  return {
    mcpEndpoint: endpoint,
    preferredRuntime: undefined,
    availableRuntimes: new Map()
  };
}

async function callTool(self, tool, args, runtime) {
  let match = self.preferredRuntime;
  let targetRuntime = runtime !== undefined ? runtime : (
      match !== undefined ? match : undefined
    );
  let payload = {
    jsonrpc: "2.0",
    method: "tools/call",
    params: {
      name: tool,
      arguments: {
        args: args,
        runtime: targetRuntime
      }
    },
    id: Date.now()
  };
  let response = await fetch(self.mcpEndpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(payload)
  });
  if (!response.ok) {
    Pervasives.failwith("MCP API error");
  }
  await response.json();
  return result.result;
}

async function run(self, image) {
  return await callTool(self, "container_run", {
    image: image
  }, undefined);
}

let PolyContainerMcp = {
  make: make,
  callTool: callTool,
  run: run
};

export {
  Types,
  runtimePriority,
  PolyContainerMcp,
}
/* No side effect */
