// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE


let methodInitialize = "initialize";

let methodListTools = "tools/list";

let methodCallTool = "tools/call";

let methodNotification = "notifications/message";

export {
  methodInitialize,
  methodListTools,
  methodCallTool,
  methodNotification,
}
/* No side effect */
