// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE


let svalinnRun_inputSchema = {
  type_: "object",
  properties: {
    image: {
      type: "string",
      description: "Container image reference"
    },
    name: {
      type: "string",
      description: "Optional container name"
    },
    command: {
      type: "array",
      items: {
        type: "string"
      },
      description: "Command to run"
    },
    detach: {
      type: "boolean",
      description: "Run in background"
    },
    removeOnExit: {
      type: "boolean",
      description: "Remove container when it exits"
    }
  },
  required: ["image"]
};

let svalinnRun = {
  name: "svalinn_run",
  description: "Run a container with edge validation. Validates request against verified-container-spec, checks edge policy, then delegates to Vörðr.",
  inputSchema: svalinnRun_inputSchema
};

let svalinnPs_inputSchema = {
  type_: "object",
  properties: {
    all: {
      type: "boolean",
      description: "Show all containers (default shows only running)"
    },
    filter: {
      type: "string",
      description: "Filter containers by name or image"
    }
  },
  required: []
};

let svalinnPs = {
  name: "svalinn_ps",
  description: "List containers managed by Vörðr",
  inputSchema: svalinnPs_inputSchema
};

let svalinnStop_inputSchema = {
  type_: "object",
  properties: {
    containerId: {
      type: "string",
      description: "Container ID to stop"
    },
    timeout: {
      type: "integer",
      description: "Timeout in seconds before force kill"
    }
  },
  required: ["containerId"]
};

let svalinnStop = {
  name: "svalinn_stop",
  description: "Stop a running container",
  inputSchema: svalinnStop_inputSchema
};

let svalinnVerify_inputSchema = {
  type_: "object",
  properties: {
    image: {
      type: "string",
      description: "Image reference to verify"
    },
    checkSbom: {
      type: "boolean",
      description: "Check SBOM attestation"
    },
    checkSignature: {
      type: "boolean",
      description: "Check image signature"
    }
  },
  required: ["image"]
};

let svalinnVerify = {
  name: "svalinn_verify",
  description: "Verify container image signature and attestation via Vörðr",
  inputSchema: svalinnVerify_inputSchema
};

let svalinnPolicy_inputSchema = {
  type_: "object",
  properties: {
    action: {
      type: "string",
      enum: [
        "get",
        "set",
        "validate"
      ],
      description: "Policy action to perform"
    },
    policy: {
      type: "object",
      description: "Policy configuration (for set action)"
    }
  },
  required: ["action"]
};

let svalinnPolicy = {
  name: "svalinn_policy",
  description: "Manage edge security policies",
  inputSchema: svalinnPolicy_inputSchema
};

let svalinnLogs_inputSchema = {
  type_: "object",
  properties: {
    containerId: {
      type: "string",
      description: "Container ID"
    },
    tail: {
      type: "integer",
      description: "Number of lines to show from end"
    },
    since: {
      type: "string",
      description: "Show logs since timestamp"
    }
  },
  required: ["containerId"]
};

let svalinnLogs = {
  name: "svalinn_logs",
  description: "Get container logs",
  inputSchema: svalinnLogs_inputSchema
};

let svalinnExec_inputSchema = {
  type_: "object",
  properties: {
    containerId: {
      type: "string",
      description: "Container ID"
    },
    command: {
      type: "array",
      items: {
        type: "string"
      },
      description: "Command to execute"
    }
  },
  required: [
    "containerId",
    "command"
  ]
};

let svalinnExec = {
  name: "svalinn_exec",
  description: "Execute a command in a running container",
  inputSchema: svalinnExec_inputSchema
};

let svalinnRm_inputSchema = {
  type_: "object",
  properties: {
    containerId: {
      type: "string",
      description: "Container ID to remove"
    },
    force: {
      type: "boolean",
      description: "Force removal even if running"
    }
  },
  required: ["containerId"]
};

let svalinnRm = {
  name: "svalinn_rm",
  description: "Remove a stopped container",
  inputSchema: svalinnRm_inputSchema
};

let allTools = [
  svalinnRun,
  svalinnPs,
  svalinnStop,
  svalinnVerify,
  svalinnPolicy,
  svalinnLogs,
  svalinnExec,
  svalinnRm
];

export {
  svalinnRun,
  svalinnPs,
  svalinnStop,
  svalinnVerify,
  svalinnPolicy,
  svalinnLogs,
  svalinnExec,
  svalinnRm,
  allTools,
}
/* No side effect */
