// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as VordrTypes from "./VordrTypes.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(config) {
  return {
    config: config,
    requestId: 0
  };
}

function fromEnv() {
  let e = (Deno.env.toObject())["VORDR_ENDPOINT"];
  let endpoint = e !== undefined ? Primitive_option.valFromOption(e) : "http://localhost:8080";
  return {
    config: {
      endpoint: endpoint,
      timeout: 30000
    },
    requestId: 0
  };
}

function nextId(client) {
  client.requestId = client.requestId + 1 | 0;
  return client.requestId;
}

async function callTool(client, toolName, args) {
  let request_params = {
    name: toolName,
    arguments: args
  };
  let request_id = nextId(client);
  let request = {
    jsonrpc: "2.0",
    method: "tools/call",
    params: request_params,
    id: request_id
  };
  let response = await fetch(client.config.endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(request)
  });
  let json = await response.json();
  let err = json.error;
  if (err !== undefined) {
    return Stdlib_JsError.throwWithMessage(err.message);
  }
  let r = json.result;
  if (r !== undefined) {
    return r;
  } else {
    return null;
  }
}

async function ping(client) {
  try {
    await fetch(client.config.endpoint + `/health`, {
      method: "GET"
    });
    return true;
  } catch (exn) {
    return false;
  }
}

async function listContainers(client) {
  return [];
}

async function listImages(_client) {
  return [];
}

async function runContainer(client, request) {
  let createArgs = {
    image: request.imageName,
    name: request.name,
    config: {
      privileged: false,
      readOnlyRoot: true
    }
  };
  let createResult = await callTool(client, VordrTypes.toolContainerCreate, createArgs);
  let containerId = createResult.containerId;
  await callTool(client, VordrTypes.toolContainerStart, {
    containerId: containerId
  });
  return {
    id: containerId,
    name: Core__Option.getOr(request.name, containerId),
    image: request.imageName,
    imageDigest: request.imageDigest,
    state: "running",
    policyVerdict: "allowed",
    createdAt: Date.now().toString(),
    startedAt: Date.now().toString()
  };
}

async function verifyImage(client, imageRef, _digest) {
  let args = {
    image: imageRef,
    checkSbom: true,
    checkSignature: true
  };
  return await callTool(client, VordrTypes.toolVerifyImage, args);
}

async function stopContainer(client, containerId) {
  await callTool(client, VordrTypes.toolContainerStop, {
    containerId: containerId
  });
}

async function removeContainer(client, containerId) {
  await callTool(client, VordrTypes.toolContainerRemove, {
    containerId: containerId
  });
}

async function inspectContainer(_client, containerId) {
  return {
    id: containerId,
    name: containerId,
    image: "unknown",
    imageDigest: "",
    state: "running",
    policyVerdict: "unknown",
    createdAt: undefined,
    startedAt: undefined
  };
}

async function requestAuthorization(client, operation, threshold, signers) {
  let args = {
    operation: operation,
    threshold: threshold,
    signers: signers
  };
  return await callTool(client, VordrTypes.toolRequestAuth, args);
}

async function submitSignature(client, share) {
  return await callTool(client, VordrTypes.toolSubmitSignature, share);
}

async function startMonitor(client, config) {
  return await callTool(client, VordrTypes.toolMonitorStart, config);
}

async function stopMonitor(client, containerId) {
  return await callTool(client, VordrTypes.toolMonitorStop, {
    containerId: containerId
  });
}

async function getAnomalies(client, containerId, severity) {
  let args = {
    containerId: containerId,
    severity: severity
  };
  return await callTool(client, VordrTypes.toolGetAnomalies, args);
}

async function rollback(client, containerId, steps) {
  let args = {
    containerId: containerId,
    steps: steps
  };
  return await callTool(client, VordrTypes.toolRollback, args);
}

async function previewRollback(client, containerId) {
  let args = {
    containerId: containerId
  };
  return await callTool(client, VordrTypes.toolPreviewRollback, args);
}

let client = fromEnv();

let defaultConfig = {
  endpoint: "http://localhost:8080",
  timeout: 30000
};

export {
  make,
  defaultConfig,
  fromEnv,
  nextId,
  callTool,
  ping,
  listContainers,
  listImages,
  runContainer,
  verifyImage,
  stopContainer,
  removeContainer,
  inspectContainer,
  requestAuthorization,
  submitSignature,
  startMonitor,
  stopMonitor,
  getAnomalies,
  rollback,
  previewRollback,
  client,
}
/* client Not a pure module */
