// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE


let toolContainerCreate = "vordr_container_create";

let toolContainerStart = "vordr_container_start";

let toolContainerStop = "vordr_container_stop";

let toolContainerRemove = "vordr_container_remove";

let toolVerifyImage = "vordr_verify_image";

let toolVerifyConfig = "vordr_verify_config";

let toolRequestAuth = "vordr_request_authorization";

let toolSubmitSignature = "vordr_submit_signature";

let toolMonitorStart = "vordr_monitor_start";

let toolMonitorStop = "vordr_monitor_stop";

let toolGetAnomalies = "vordr_get_anomalies";

let toolRollback = "vordr_rollback";

let toolPreviewRollback = "vordr_preview_rollback";

export {
  toolContainerCreate,
  toolContainerStart,
  toolContainerStop,
  toolContainerRemove,
  toolVerifyImage,
  toolVerifyConfig,
  toolRequestAuth,
  toolSubmitSignature,
  toolMonitorStart,
  toolMonitorStop,
  toolGetAnomalies,
  toolRollback,
  toolPreviewRollback,
}
/* No side effect */
