// SPDX-License-Identifier: MPL-2.0
// Generated by ReScript, PLEASE EDIT WITH CARE


function main() {
  console.log("Svalinn Gateway Activated (ReScript Pivot)");
}

export {
  main,
}
/* No side effect */
