// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jwt from "./Jwt.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let Hono = {};

async function authenticateBearerToken(c, config) {
  let auth = c["req.header"]("Authorization");
  if (auth === undefined) {
    return {
      authenticated: false,
      method: "oidc",
      error: "No bearer token provided"
    };
  }
  if (!auth.startsWith("Bearer ")) {
    return {
      authenticated: false,
      method: "oidc",
      error: "No bearer token provided"
    };
  }
  let token = auth.substring(7, auth.length);
  try {
    let oidc = config.oidc;
    let payload = oidc !== undefined ? await Jwt.verifyJwt(token, oidc) : (Jwt.decodeJwt(token), decoded.payload);
    return {
      authenticated: true,
      method: "oidc",
      subject: payload.sub,
      scopes: Stdlib_Option.getOr(Stdlib_Option.map(payload.scope, s => s.split(" ")), []),
      token: payload
    };
  } catch (exn) {
    return {
      authenticated: false,
      method: "oidc",
      error: "Token verification failed"
    };
  }
}

function authMiddleware(config) {
  return async (c, next) => {
    if (!config.enabled) {
      return await next();
    }
    let result = {
      authenticated: false,
      method: "none",
      error: "No authentication provided"
    };
    for (let i = 0, i_finish = config.methods.length; i < i_finish; ++i) {
      let method = Belt_Array.getExn(config.methods, i);
      let res = method === "none" ? ({
          authenticated: true,
          method: "none"
        }) : (
          method === "oauth2" || method === "oidc" ? await authenticateBearerToken(c, config) : ({
              authenticated: false,
              method: "none",
              error: "Method not implemented"
            })
        );
      if (res.authenticated) {
        result = res;
      }
    }
    c.set("authResult", result);
    if (result.authenticated) {
      return await next();
    } else {
      return await c.json({
        error: "Unauthorized",
        message: result.error
      }, 401);
    }
  };
}

export {
  Hono,
  authenticateBearerToken,
  authMiddleware,
}
/* Jwt Not a pure module */
