// Generated by ReScript, PLEASE EDIT WITH CARE


let Types = {};

let defaultRoles = [
  {
    name: "admin",
    permissions: [{
        resource: "*",
        actions: [
          "create",
          "read",
          "update",
          "delete",
          "execute"
        ]
      }],
    description: "Full access to all resources"
  },
  {
    name: "operator",
    permissions: [
      {
        resource: "containers",
        actions: [
          "create",
          "read",
          "update",
          "delete",
          "execute"
        ]
      },
      {
        resource: "images",
        actions: ["read"]
      },
      {
        resource: "policies",
        actions: ["read"]
      }
    ],
    description: "Can manage containers but not policies"
  },
  {
    name: "viewer",
    permissions: [
      {
        resource: "containers",
        actions: ["read"]
      },
      {
        resource: "images",
        actions: ["read"]
      },
      {
        resource: "policies",
        actions: ["read"]
      }
    ],
    description: "Read-only access"
  }
];

export {
  Types,
  defaultRoles,
}
/* No side effect */
