// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";

let Types = {};

let Subtle = {};

let Crypto = {
  Subtle: Subtle
};

let jwksCache = new Map();

async function fetchJwks(jwksUri) {
  let now = Date.now();
  let cached = jwksCache.get(jwksUri);
  if (cached !== undefined && cached.expiresAt > now) {
    return cached.jwks;
  }
  let response = await fetch(jwksUri, {
    method: "GET"
  });
  if (!response.ok) {
    Pervasives.failwith(`Failed to fetch JWKS: ` + response.status.toString());
  }
  let jwks = (await response.json());
  jwksCache.set(jwksUri, {
    jwks: jwks,
    expiresAt: now + 3600000.0
  });
  return jwks;
}

function base64UrlDecode(str) {
  let base64 = str.replace(/-/g, "+").replace(/_/g, "/");
  let mod4 = base64.length % 4;
  let padding = mod4 > 0 ? "=".repeat(4 - mod4 | 0) : "";
  let binary = atob(base64 + padding);
  let len = binary.length;
  let bytes = new Uint8Array(len);
  (((function() { for (var i = 0; i < len; i++) { bytes[i] = binary.charCodeAt(i); } })()));
  return bytes;
}

function parseJwtSegments(token) {
  let parts = token.split(".");
  if (parts.length !== 3) {
    Pervasives.failwith("Invalid JWT format");
  }
  let headerB64 = parts[0];
  let payloadB64 = parts[1];
  let signatureB64 = parts[2];
  let decodePart = p => {
    atob(p.replace(/-/g, "+").replace(/_/g, "/"));
    return (JSON.parse(jsonStr));
  };
  return {
    headerB64: headerB64,
    payloadB64: payloadB64,
    signatureB64: signatureB64,
    header: decodePart(headerB64),
    payload: decodePart(payloadB64)
  };
}

function algToWebCrypto(alg) {
  switch (alg) {
    case "ES256" :
      return {
        TAG: "Ok",
        _0: [
          {name: "ECDSA", namedCurve: "P-256", hash: "SHA-256"},
          {name: "ECDSA", hash: "SHA-256"}
        ]
      };
    case "ES384" :
      return {
        TAG: "Ok",
        _0: [
          {name: "ECDSA", namedCurve: "P-384", hash: "SHA-384"},
          {name: "ECDSA", hash: "SHA-384"}
        ]
      };
    case "ES512" :
      return {
        TAG: "Ok",
        _0: [
          {name: "ECDSA", namedCurve: "P-521", hash: "SHA-512"},
          {name: "ECDSA", hash: "SHA-512"}
        ]
      };
    case "EdDSA" :
      return {
        TAG: "Ok",
        _0: [
          {name: "Ed25519"},
          {name: "Ed25519"}
        ]
      };
    case "PS256" :
      return {
        TAG: "Ok",
        _0: [
          {name: "RSA-PSS", hash: "SHA-256"},
          {name: "RSA-PSS", saltLength: 32}
        ]
      };
    case "PS384" :
      return {
        TAG: "Ok",
        _0: [
          {name: "RSA-PSS", hash: "SHA-384"},
          {name: "RSA-PSS", saltLength: 48}
        ]
      };
    case "PS512" :
      return {
        TAG: "Ok",
        _0: [
          {name: "RSA-PSS", hash: "SHA-512"},
          {name: "RSA-PSS", saltLength: 64}
        ]
      };
    case "RS256" :
      return {
        TAG: "Ok",
        _0: [
          {name: "RSASSA-PKCS1-v1_5", hash: "SHA-256"},
          {name: "RSASSA-PKCS1-v1_5"}
        ]
      };
    case "RS384" :
      return {
        TAG: "Ok",
        _0: [
          {name: "RSASSA-PKCS1-v1_5", hash: "SHA-384"},
          {name: "RSASSA-PKCS1-v1_5"}
        ]
      };
    case "RS512" :
      return {
        TAG: "Ok",
        _0: [
          {name: "RSASSA-PKCS1-v1_5", hash: "SHA-512"},
          {name: "RSASSA-PKCS1-v1_5"}
        ]
      };
    case "none" :
      return {
        TAG: "Error",
        _0: "Algorithm 'none' is rejected for security reasons"
      };
    default:
      return {
        TAG: "Error",
        _0: `Unsupported JWT algorithm: ` + alg
      };
  }
}

async function verifyJwt(token, config) {
  let decoded = parseJwtSegments(token);
  let alg = decoded.header.alg;
  let kid = decoded.header.kid;
  let pair = algToWebCrypto(alg);
  let match;
  match = pair.TAG === "Ok" ? pair._0 : Pervasives.failwith(pair._0);
  let payload = decoded.payload;
  let now = Date.now() / 1000.0;
  let exp = payload.exp;
  if (exp !== undefined && exp < now) {
    Pervasives.failwith("Token expired");
  }
  if (payload.iss !== config.issuer) {
    Pervasives.failwith(`Invalid issuer: expected ` + config.issuer + `, got ` + payload.iss);
  }
  let jwks = await fetchJwks(config.jwksUri);
  let keyOpt = jwks.keys.find(k => k.kid === kid);
  let jwk = keyOpt !== undefined ? keyOpt : Pervasives.failwith(`Key not found: ` + kid);
  let formatJwk = "jwk";
  let cryptoKey = await crypto.subtle.importKey(formatJwk, jwk, match[0], false, ["verify"]);
  let signingInput = new TextEncoder().encode(decoded.headerB64 + "." + decoded.payloadB64);
  let signatureBytes = base64UrlDecode(decoded.signatureB64);
  let ok = await crypto.subtle.verify(match[1], cryptoKey, signatureBytes, signingInput);
  if (!ok) {
    Pervasives.failwith("JWT signature verification failed");
  }
  return payload;
}

let jwksCacheTtl = 3600000.0;

export {
  Types,
  Crypto,
  jwksCache,
  jwksCacheTtl,
  fetchJwks,
  base64UrlDecode,
  parseJwtSegments,
  algToWebCrypto,
  verifyJwt,
}
/* jwksCache Not a pure module */
