// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";

let Types = {};

let Subtle = {};

let Crypto = {
  Subtle: Subtle
};

let jwksCache = new Map();

async function fetchJwks(jwksUri) {
  let now = Date.now();
  let cached = jwksCache.get(jwksUri);
  if (cached !== undefined && cached.expiresAt > now) {
    return cached.jwks;
  }
  let response = await fetch(jwksUri, {
    method: "GET"
  });
  if (!response.ok) {
    Pervasives.failwith(`Failed to fetch JWKS: ` + response.status.toString());
  }
  let jwks = (await response.json());
  jwksCache.set(jwksUri, {
    jwks: jwks,
    expiresAt: now + 3600000.0
  });
  return jwks;
}

function base64UrlDecode(str) {
  let base64 = str.replace(/-/g, "+").replace(/_/g, "/");
  let mod4 = base64.length % 4;
  let padding = mod4 > 0 ? "=".repeat(4 - mod4 | 0) : "";
  let binary = atob(base64 + padding);
  let bytes = new Uint8Array(binary.length);
  for (let _i = 0, _i_finish = binary.length; _i < _i_finish; ++_i) {
    ((bytes[i] = binary.charCodeAt(i)));
  }
  return bytes;
}

function decodeJwt(token) {
  let parts = token.split(".");
  if (parts.length !== 3) {
    Pervasives.failwith("Invalid JWT format");
  }
  let decodePart = p => JSON.parse(atob(p.replace(/-/g, "+").replace(/_/g, "/")));
  return {
    header: decodePart(parts[0]),
    payload: decodePart(parts[1])
  };
}

async function verifyJwt(token, config) {
  decodeJwt(token);
  let payload = decoded.payload;
  let now = Date.now() / 1000.0;
  let exp = payload.exp;
  if (exp !== undefined && exp < now) {
    Pervasives.failwith("Token expired");
  }
  if (payload.iss !== config.issuer) {
    Pervasives.failwith(`Invalid issuer: expected ` + config.issuer + `, got ` + payload.iss);
  }
  let jwks = await fetchJwks(config.jwksUri);
  let kid = header.kid;
  let keyOpt = jwks.keys.find(k => k.kid === kid);
  if (keyOpt !== undefined) {
    return payload;
  } else {
    return Pervasives.failwith(`Key not found: ` + kid);
  }
}

let jwksCacheTtl = 3600000.0;

export {
  Types,
  Crypto,
  jwksCache,
  jwksCacheTtl,
  fetchJwks,
  base64UrlDecode,
  decodeJwt,
  verifyJwt,
}
/* jwksCache Not a pure module */
