// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

let URLSearchParams = {};

function getAuthorizationUrl(config, state, nonce) {
  let params = new URLSearchParams({
    response_type: "code",
    client_id: config.clientId,
    redirect_uri: config.redirectUri,
    scope: config.scopes.join(" "),
    state: state
  });
  if (nonce !== undefined) {
    params.set("nonce", nonce);
  }
  return config.authorizationEndpoint + `?` + params.toString();
}

async function exchangeCode(config, code) {
  let params = new URLSearchParams({
    grant_type: "authorization_code",
    code: code,
    redirect_uri: config.redirectUri,
    client_id: config.clientId,
    client_secret: config.clientSecret
  });
  let response = await fetch(config.tokenEndpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    body: params.toString()
  });
  if (!response.ok) {
    let error = await response.text();
    Pervasives.failwith(`Token exchange failed: ` + error);
  }
  return await response.json().then(json => Promise.resolve(json));
}

function generateState() {
  new Uint8Array(32);
  ((crypto.getRandomValues(array)));
  return Core__Array.fromInitializer(32, _i => (_array[_i]).toString(16).padStart(2, "0")).join("");
}

function generateNonce() {
  return generateState();
}

export {
  URLSearchParams,
  getAuthorizationUrl,
  exchangeCode,
  generateState,
  generateNonce,
}
/* No side effect */
